//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrometheusWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Homework
    {
        /// <summary>
        /// To store homework details.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Homework()
        {
            this.Assignments = new HashSet<Assignment>();
        }
    
        public int HomeWorkID { get; set; }
        [Required(ErrorMessage = "Description is compulsory field")]
        public string Description { get; set; }
        [Required(ErrorMessage = "DeadLine is compulsory field")]
        [DeadlineValidator]
        public Nullable<System.DateTime> Deadline { get; set; }
        [Required(ErrorMessage = "Required Time is compulsory field")]
        public Nullable<System.TimeSpan> ReqTime { get; set; }
        [Required(ErrorMessage = "Description is compulsory field")]
        public string LongDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
    }
}
