//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrometheusWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        /// <summary>
        /// to store student details.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int StudentID { get; set; }
        [Required(ErrorMessage = "Firstname is compulsory field")]
        public string FName { get; set; }
        [Required(ErrorMessage = "LastName is compulsory field")]
        public string LName { get; set; }
        [Required(ErrorMessage = "Address is compulsory field")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Date of Birth is compulsory field")]
        [studentDobvalidator]
        public Nullable<System.DateTime> DOB { get; set; }
        [Required(ErrorMessage = "City is compulsory field")]
        public string City { get; set; }
        [Required(ErrorMessage = "Password is compulsory field")]
        [RegularExpression("[A-Za-z0-9]{5,10}", ErrorMessage = "Invalid Password, length should be between 5 and 10")]
        public string Password { get; set; }      
        [Required(ErrorMessage = "MobileNo is compulsory field")]
        [RegularExpression("[9,8,7][0-9]{9}$", ErrorMessage = "Invalid mobile number")]
        public string MobileNo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
